import {
  type RouteConfig,
  route,
  index,
  layout,
  prefix,
} from "@react-router/dev/routes";

export default [
  route("wholesale", "routes/redirects/wholesale.tsx"),
  route("wholesale/:state", "routes/redirects/wholesale.$state.tsx"),
  route("wholesale/:state/:city", "routes/redirects/wholesale.$state.$city.tsx"),

  route("products.json", "routes/products.json.ts"),
  ...prefix("feeds", [
    route("products.xml", "routes/feeds/products.xml.ts"),
    route("google-merchant-products.xml", "routes/feeds/google-merchant-products.xml.ts"),
  ]),

  ...prefix("api", [
    route("auth/*", "routes/api/auth.ts"),
    route("checkout", "routes/api/checkout.ts"),
    route("create-payment", "routes/api/create-payment.ts"),
    route("payment/verify", "routes/api/payment.verify.ts"),
    route("payment/refund", "routes/api/payment.refund.ts"),
    route("payment/webhook", "routes/api/payment.webhook.ts"),
    route("subscription/webhook", "routes/api/subscription.webhook.ts"),
    route("subscription/create", "routes/api/subscription.create.ts"),
    route("subscription/create-upfront", "routes/api/subscription.create-upfront.ts"),
    route("subscription/list", "routes/api/subscription.list.ts"),
    route("subscription/manage", "routes/api/subscription.manage.ts"),
    route("subscription/status/:subscriptionId", "routes/api/subscription.status.$subscriptionId.ts"),
    route("validate-coupon", "routes/api/validate-coupon.ts"),
    route("contact", "routes/api/contact.ts"),
    route("reviews", "routes/api/reviews.ts"),
    route("webhooks/feature", "routes/api/webhooks.feature.ts"),
  ]),

  layout("routes/marketing/layout.tsx", [
    index("routes/marketing/home.tsx"),
    route("about", "routes/marketing/about.tsx"),
    route("careers", "routes/marketing/careers.tsx"),
    route("cart", "routes/marketing/cart.tsx"),
    route("checkout", "routes/marketing/checkout.tsx"),
    route("contact", "routes/marketing/contact.tsx"),
    route("distributor-franchise", "routes/marketing/distributor-franchise.tsx"),
    route("fundraisers", "routes/marketing/fundraisers.tsx"),
    route("how-to-use", "routes/marketing/how-to-use.tsx"),
    route("locations", "routes/marketing/locations.tsx"),
    route("payment/failure", "routes/marketing/payment-failure.tsx"),
    route("payment/success", "routes/marketing/payment-success.tsx"),
    route("privacy", "routes/marketing/privacy.tsx"),
    route("return-policy", "routes/marketing/return-policy.tsx"),
    route("social-responsibility", "routes/marketing/social-responsibility.tsx"),
    route("sites", "routes/marketing/sites.tsx"),
    route("team", "routes/marketing/team.tsx"),
    route("terms", "routes/marketing/terms.tsx"),
    route("accessories", "routes/marketing/accessories.tsx"),
    route("green-wholesale-coffee", "routes/marketing/green-wholesale-coffee.tsx"),

    route("roasted-wholesale-coffee", "routes/marketing/roasted-wholesale-coffee.tsx"),
    route("roasted-wholesale-coffee/:state", "routes/marketing/roasted-wholesale-coffee.$state.tsx"),
    route("roasted-wholesale-coffee/:state/:city", "routes/marketing/roasted-wholesale-coffee.$state.$city.tsx"),

    route("roasted-coffee-beans-for-cafes", "routes/marketing/roasted-coffee-beans-for-cafes.tsx"),
    route("roasted-coffee-beans-for-cafes/:city", "routes/marketing/roasted-coffee-beans-for-cafes.$city.tsx"),
    route("ground-coffee-for-cafes/:city", "routes/marketing/ground-coffee-for-cafes.$city.tsx"),

    route("products", "routes/marketing/products-index.tsx"),
    route("products/:slug", "routes/marketing/products.$slug.tsx"),
    route("green-coffee/:slug", "routes/marketing/products.$slug.tsx", {
      id: "green-coffee-slug",
    }),

    route("glossary", "routes/marketing/glossary-index.tsx"),
    route("glossary/:slug", "routes/marketing/glossary.$slug.tsx"),

    route("guides", "routes/marketing/guides-index.tsx"),
    route("guides/best-black-coffee-for-fatty-liver", "routes/marketing/guides/best-black-coffee-for-fatty-liver.mdx"),
    route("guides/black-coffee-liver-health", "routes/marketing/guides/black-coffee-liver-health.mdx"),
    route("guides/brewing-the-perfect-cup", "routes/marketing/guides/brewing-the-perfect-cup.mdx"),
    route("guides/ctc-vs-loose-leaf-tea", "routes/marketing/guides/ctc-vs-loose-leaf-tea.mdx"),
    route("guides/instant-vs-brewed-coffee", "routes/marketing/guides/instant-vs-brewed-coffee.mdx"),
    route("guides/best-black-coffee-for-weight-loss", "routes/marketing/guides/best-black-coffee-for-weight-loss.mdx"),
    route("guides/best-coffee-for-gym", "routes/marketing/guides/best-coffee-for-gym.mdx"),
    route("guides/best-coffee-before-workout", "routes/marketing/guides/best-coffee-before-workout.mdx"),
    route("guides/best-coffee-for-caffeine", "routes/marketing/guides/best-coffee-for-caffeine.mdx"),
    route("guides/highest-caffeine-coffee-in-india", "routes/marketing/guides/highest-caffeine-coffee-in-india.mdx"),
    route("guides/best-coffee-for-energy", "routes/marketing/guides/best-coffee-for-energy.mdx"),
    route("guides/best-black-coffee-in-india", "routes/marketing/guides/best-black-coffee-in-india.mdx"),
    route("guides/best-coffee-beans-in-india", "routes/marketing/guides/best-coffee-beans-in-india.mdx"),
    route("guides/best-filter-coffee-in-india", "routes/marketing/guides/best-filter-coffee-in-india.mdx"),
    route("guides/best-filter-coffee-powder-in-india", "routes/marketing/guides/best-filter-coffee-powder-in-india.mdx"),
    route("guides/best-coffee-for-drinking-black", "routes/marketing/guides/best-coffee-for-drinking-black.mdx"),
    route("guides/best-strong-coffee-in-india", "routes/marketing/guides/best-strong-coffee-in-india.mdx"),
    route("guides/arabica-vs-robusta", "routes/marketing/guides/arabica-vs-robusta.mdx"),
    route("guides/arabica-vs-robusta-caffeine", "routes/marketing/guides/arabica-vs-robusta-caffeine.mdx"),
    route("guides/coffee-vs-chicory", "routes/marketing/guides/coffee-vs-chicory.mdx"),
    route("guides/best-coffee-for-focus-and-studying", "routes/marketing/guides/best-coffee-for-focus-and-studying.mdx"),
    route("guides/best-coffee-for-metabolism", "routes/marketing/guides/best-coffee-for-metabolism.mdx"),
    route("guides/best-coffee-for-belly-fat", "routes/marketing/guides/best-coffee-for-belly-fat.mdx"),
    route("guides/best-coffee-for-staying-awake", "routes/marketing/guides/best-coffee-for-staying-awake.mdx"),
    route("guides/best-black-coffee-without-sugar", "routes/marketing/guides/best-black-coffee-without-sugar.mdx"),
    route("guides/best-coffee-beans-for-black-coffee", "routes/marketing/guides/best-coffee-beans-for-black-coffee.mdx"),
    route("guides/best-smooth-black-coffee", "routes/marketing/guides/best-smooth-black-coffee.mdx"),
    route("guides/best-south-indian-filter-coffee", "routes/marketing/guides/best-south-indian-filter-coffee.mdx"),
    route("guides/best-filter-coffee-for-home", "routes/marketing/guides/best-filter-coffee-for-home.mdx"),
    route("guides/best-arabica-coffee-in-india", "routes/marketing/guides/best-arabica-coffee-in-india.mdx"),
    route("guides/best-robusta-coffee-in-india", "routes/marketing/guides/best-robusta-coffee-in-india.mdx"),
    route("guides/best-medium-roast-coffee-in-india", "routes/marketing/guides/best-medium-roast-coffee-in-india.mdx"),
    route("guides/light-roast-vs-dark-roast-coffee", "routes/marketing/guides/light-roast-vs-dark-roast-coffee.mdx"),
    route("guides/black-coffee-vs-milk-coffee", "routes/marketing/guides/black-coffee-vs-milk-coffee.mdx"),
    route("guides/filter-coffee-vs-instant-coffee", "routes/marketing/guides/filter-coffee-vs-instant-coffee.mdx"),
    route("guides/best-coffee-for-french-press", "routes/marketing/guides/best-coffee-for-french-press.mdx"),
    route("guides/best-coffee-for-cold-brew", "routes/marketing/guides/best-coffee-for-cold-brew.mdx"),
    route("guides/best-coffee-for-moka-pot", "routes/marketing/guides/best-coffee-for-moka-pot.mdx"),
    route("guides/best-coffee-for-pour-over", "routes/marketing/guides/best-coffee-for-pour-over.mdx"),
    route("guides/best-coffee-for-espresso-at-home", "routes/marketing/guides/best-coffee-for-espresso-at-home.mdx"),
    route("guides/black-coffee-vs-espresso", "routes/marketing/guides/black-coffee-vs-espresso.mdx"),
    route("guides/best-coffee-for-beginners", "routes/marketing/guides/best-coffee-for-beginners.mdx"),
    route("guides/best-coffee-under-500-in-india", "routes/marketing/guides/best-coffee-under-500-in-india.mdx"),
    route("guides/how-to-choose-coffee", "routes/marketing/guides/how-to-choose-coffee.mdx"),
    route("guides/is-black-coffee-good-for-you", "routes/marketing/guides/is-black-coffee-good-for-you.mdx"),
    route("guides/black-coffee-benefits", "routes/marketing/guides/black-coffee-benefits.mdx"),
    route("guides/how-much-caffeine-in-a-cup-of-coffee", "routes/marketing/guides/how-much-caffeine-in-a-cup-of-coffee.mdx"),
    route("guides/best-time-to-drink-black-coffee", "routes/marketing/guides/best-time-to-drink-black-coffee.mdx"),
    route("guides/best-coffee-for-intermittent-fasting", "routes/marketing/guides/best-coffee-for-intermittent-fasting.mdx"),
    route("guides/best-coffee-for-morning-workout", "routes/marketing/guides/best-coffee-for-morning-workout.mdx"),
    route("guides/best-coffee-for-athletes", "routes/marketing/guides/best-coffee-for-athletes.mdx"),
    route("guides/best-coffee-for-running", "routes/marketing/guides/best-coffee-for-running.mdx"),
    route("guides/best-coffee-for-the-office", "routes/marketing/guides/best-coffee-for-the-office.mdx"),
    route("guides/best-coffee-for-night-shift", "routes/marketing/guides/best-coffee-for-night-shift.mdx"),
    route("guides/best-coffee-for-milk-coffee", "routes/marketing/guides/best-coffee-for-milk-coffee.mdx"),
    route("guides/best-ground-coffee-for-milk", "routes/marketing/guides/best-ground-coffee-for-milk.mdx"),
    route("guides/natural-vs-washed-coffee", "routes/marketing/guides/natural-vs-washed-coffee.mdx"),
    route("guides/what-is-honey-processed-coffee", "routes/marketing/guides/what-is-honey-processed-coffee.mdx"),
    route("guides/single-origin-vs-blend-coffee", "routes/marketing/guides/single-origin-vs-blend-coffee.mdx"),
    route("guides/how-to-make-black-coffee", "routes/marketing/guides/how-to-make-black-coffee.mdx"),
    route("guides/coffee-and-sleep", "routes/marketing/guides/coffee-and-sleep.mdx"),
    route("guides/coffee-on-an-empty-stomach", "routes/marketing/guides/coffee-on-an-empty-stomach.mdx"),
    route("guides/how-to-store-coffee", "routes/marketing/guides/how-to-store-coffee.mdx"),
    route("guides/coffee-grind-size-guide", "routes/marketing/guides/coffee-grind-size-guide.mdx"),
    route("guides/how-to-reset-caffeine-tolerance", "routes/marketing/guides/how-to-reset-caffeine-tolerance.mdx"),
    route("guides/best-coffee-for-aeropress", "routes/marketing/guides/best-coffee-for-aeropress.mdx"),
    route("guides/decaf-coffee-in-india", "routes/marketing/guides/decaf-coffee-in-india.mdx"),
    route("guides/chicory-coffee-benefits", "routes/marketing/guides/chicory-coffee-benefits.mdx"),
    route("guides/best-coffee-for-fat-loss", "routes/marketing/guides/best-coffee-for-fat-loss.mdx"),
    route("guides/is-coffee-a-good-pre-workout", "routes/marketing/guides/is-coffee-a-good-pre-workout.mdx"),
    route("guides/best-coffee-powder-for-black-coffee", "routes/marketing/guides/best-coffee-powder-for-black-coffee.mdx"),
    route("guides/best-strong-filter-coffee", "routes/marketing/guides/best-strong-filter-coffee.mdx"),
    route("guides/best-dark-roast-coffee-in-india", "routes/marketing/guides/best-dark-roast-coffee-in-india.mdx"),
    route("guides/best-light-roast-coffee-in-india", "routes/marketing/guides/best-light-roast-coffee-in-india.mdx"),
    route("guides/best-arabica-robusta-blend-coffee", "routes/marketing/guides/best-arabica-robusta-blend-coffee.mdx"),
    route("guides/black-coffee-for-diabetes", "routes/marketing/guides/black-coffee-for-diabetes.mdx"),
    route("guides/is-filter-coffee-good-for-you", "routes/marketing/guides/is-filter-coffee-good-for-you.mdx"),
    route("guides/best-instant-coffee-alternatives", "routes/marketing/guides/best-instant-coffee-alternatives.mdx"),
    route("guides/best-coffee-for-weight-management", "routes/marketing/guides/best-coffee-for-weight-management.mdx"),
    route("guides/best-non-bitter-coffee", "routes/marketing/guides/best-non-bitter-coffee.mdx"),

    route("subscribe/:productSlug", "routes/marketing/subscribe.$productSlug.tsx"),

    route("auth/login", "routes/marketing/auth/login.tsx"),
    route("auth/register", "routes/marketing/auth/register.tsx"),
    route("auth/forgot-password", "routes/marketing/auth/forgot-password.tsx"),
    route("auth/reset-password", "routes/marketing/auth/reset-password.tsx"),

    layout("routes/marketing/account/layout.tsx", [
      route("account/subscriptions", "routes/marketing/account/subscriptions.tsx"),
    ]),

    // Location pages ([state]/[slug] and [state]/[slug]/[topic] from the Next
    // app) must come last - they're single/double dynamic segments that would
    // otherwise shadow every static path above.
    route(":state/:slug", "routes/marketing/$state.$slug.tsx"),
    route(":state/:slug/:topic", "routes/marketing/$state.$slug.$topic.tsx"),

    // Catch-all route for handling 404s gracefully without internal router errors
    route("*", "routes/not-found.tsx"),
  ]),
] satisfies RouteConfig;

